= Configure AMQ Streams 7 and OCP 3.11
:toc:

.Note about AMQ Streams 7
****
AMQ Streams makes it easy to run Apache Kafka on OpenShift. Apache Kafka is a popular platform for streaming data delivery and processing. For more information about Apache Kafka, see the Apache Kafka website.

AMQ Streams is based on Apache Kafka 2.0.1 and consists of three main components:

* *Cluster Operator*
Responsible for deploying and managing Apache Kafka clusters within OpenShift cluster.

* *Topic Operator*
Responsible for managing Kafka topics within a Kafka cluster running within OpenShift cluster.

* *User Operator*
Responsible for managing Kafka users within a Kafka cluster running within OpenShift cluster.

****


==  Install all necessary components
===  Step 1: Download the required files

To install AMQ Streams, download and extract the amq-streams-1.1.0-ocp-install-examples.zip file from  https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=66571[AMQ Streams download site]

===  Step 2: Create a new namespace or use an existing one
[source,bash]
----
oc login -u admin -p passw0rd
oc new-project amq-streams --description="Test Project for AMQ Streams" --display-name="amq-streams"
----

===  Step 3: Replace the namespace with the correct project name
[source,bash]
----
sed -i 's/namespace: .*/namespace: amq-streams/' install/cluster-operator/*RoleBinding*.yaml
----
[NOTE]
====
*_Optional_*

Edit the file install/cluster-operator/050-Deployment-strimzi-cluster-operator.yaml and in the environment variable STRIMZI_NAMESPACE list all the OpenShift projects or Kubernetes namespaces where Cluster Operator should watch for resources. By Defulat it looks to the same namespace using
https://docs.openshift.com/container-platform/3.11/dev_guide/downward_api.html#dapi-consuming-container-values[Downward API]

[source,yaml]
----
env:
    - name: STRIMZI_NAMESPACE
        valueFrom:
          fieldRef:
           fieldPath: metadata.namespace

----
====

===  Step 4: Deploying the Kafka crt to cluster
you will need a user with 'cluster-admin' role

[source,bash]
----
oc create -f install/cluster-operator
oc create -f examples/templates/cluster-operator
----

===  Step 4: Create the kafka cluster
Using link:yamls/custom-kafka-persistent.yaml[custom-kafka-persistent.yaml] create the kafka cluster. Refer to https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/index#assembly-deployment-configuration-kafka-str[Kafka cluster configuration] for the full list of schema of the Kafka resource
[source,bash]
----
oc apply -f yamls/custom-kafka-persistent.yaml
----

==== Verify that cluster is running
[source,bash]
----
oc get kafka
oc describe kafka my-cluster
----

===  Step 5: Create the kafka Topic
Using link:yamls/kafka-topic.yaml[kafka-topic.yaml] create the kafka topic. Refer to https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/index#type-KafkaTopic-reference[KafkaTopic schema reference] for the full list of schema
[source,bash]
----
oc apply -f yamls/kafka-topic.yaml
----